VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
